[project]
name = "pytracing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.5.2",
    "matplotlib>=3.10.6",
    "scipy>=1.16.2",
    "tqdm>=4.67.1",
    "tqdm-joblib>=0.0.5",
]
